/**
 * chain.js — Kronos on-chain price client for the static terminal.
 *
 * Reads live oracle prices from a Kronos deployment over plain JSON-RPC
 * (no wallet, no dependencies) and feeds them into the MARKETS array that
 * `script.js` renders. If the RPC is unreachable, demo prices remain.
 *
 * Configure RPC via `localStorage.kronos_rpc` or `window.KRONOS_RPC`.
 * Default RPC comes from markets.bootstrap.json (`manifest.rpc`).
 *
 * Oracle map is AUTO-GENERATED by scripts/gen-app-markets.js — do not edit.
 */
(function () {
  "use strict";

  var KRONOS = {
    programId: "HEZgFANPKb5hCCDZYzz1gdnbsD7C52gAPx5GNU1ifziP",
    // market_id (== MARKETS[].name) -> oracle account pubkey
    oracles: {
      "WL500-PERP": "GF1JfkbgH9EcZXC55DZgxZgEkBBsjk1K9YasTeXsUFaB",
      "GOLD-PERP": "69LH9Z52mf25jxvrZMFAnfGp6Sw7whLGs7oKFDAjJKpY",
      "SILVER-PERP": "GUPesVEyUiPpYR6Uv5YeStMXxpU9oxZrMujASZSQvxqX",
      "PLATINUM-PERP": "FLYN91RZc8Hta45RXcqyiQxyc5nohaotLhvhrYo9zojP",
      "DIAMOND-PERP": "6d95HD5RirZraqLg7se1RXNRe8abgNcNxBFNPY3UdPxc",
      "ROLEX-SUB-PERP": "GR6QD45YKdgbQxVjzpigN22NsQqDd2TPxjsqoCiw9feJ",
      "PATEK-NAUTILUS-PERP": "5CynvHovsGzyRAhWymJWkcTStwFjHpqxeeu7YWGwJDDN",
      "AP-ROYAL-OAK-PERP": "BeKjGVEnwJRGwgRXNMHRUEBkubdAHZDezCJY4AAqUskm",
      "OMEGA-SPEEDY-PERP": "HAA3jCpcLFwTB1UCM9LtBNKuZ14z532xqwUob9fyFPR8",
      "CARTIER-SANTOS-PERP": "4DPvJKYGACSJXieqdCLyfhezzTQatJPP8FntEzSWf9yT",
      "RM-11-PERP": "4uzsVSpEYUvRiEicm2DGhmhi5MUwgUxN4xouybFCdPZm",
      "VC-OVERSEAS-PERP": "BNBvZtoCEf49iA2G9dRH2KWRZUZp3jveFG2YN9QYKfE1",
      "IWC-PILOT-PERP": "FsGmgvdkgu7P36yyCKTeZsqVTyTiLNGkViRE4tefNHyE",
      "TAG-CARRERA-PERP": "CUn8JUf882waRGQCnqWMzvw4kvAt7SfvVwLaGPMNqrot",
      "ROLEX-DAYTONA-PERP": "bRYw8BCXGbatStJBLR87RC7DXnhCLTaM259GfhiBB1M",
      "PP-ANNUAL-PERP": "3RPBk1DBkpWquPRVH78cTdytAdsxD3BLbdB65niQVAuv",
      "AP-OFFSHORE-PERP": "APBKgW6vycxVs2XtoSbKC7Xg4BXFeggbYxkz8qDQ1eBn",
      "OMEGA-SEAMASTER-PERP": "9jZyT7kPCGPWUnTbudMfuZcHZdT8yiQ61hNsNUyq1gRx",
      "CARTIER-TANK-PERP": "3Ji5xKvRtrEpoM6gSotRkzsbG1cUQ1wrkzbbvb4efyo4",
      "HUBLOT-BB-PERP": "HLwHoHsn4mCuarN4DrLkUzJKh8zJqUg7QcBUc7bC2z6v",
      "JLC-REVERSO-PERP": "3ZBRh6H9eLFfJ5UJse41WS9wvGmZ8DATLfJNnCvTXpA2",
      "PANERAI-LUM-PERP": "4FeYrkvD4U5FWMRFS39MmbvUcUUjZbVYPYag3yKcQoQQ",
      "BREITLING-NAV-PERP": "F54GsLSG9tTai34BCmBUSjhyVCGVgQdbUUzdbLWSisLf",
      "ROLEX-GMT-PERP": "FPsnY6J74x12aYdLPYHkpFFLZnp61X7CwKqUUNsfhN57",
    },
  };

  function rpcUrl() {
    try {
      if (window.KRONOS_RPC) return window.KRONOS_RPC;
      var s = window.localStorage && localStorage.getItem("kronos_rpc");
      if (s) return s;
    } catch (_) {}
    return "https://api.devnet.solana.com";
  }

  // Decode a base64 account data string and read the u64 LE oracle price
  // (offset 8, after the 8-byte Anchor discriminator). Returns USD float.
  function decodePrice(base64Data) {
    var bin = atob(base64Data);
    var lo = 0,
      hi = 0;
    for (var i = 0; i < 4; i++) lo += bin.charCodeAt(8 + i) * Math.pow(2, 8 * i);
    for (var j = 0; j < 4; j++) hi += bin.charCodeAt(12 + j) * Math.pow(2, 8 * j);
    var raw = lo + hi * Math.pow(2, 32);
    return raw / 1e6;
  }

  function getMarkets() {
    return typeof MARKETS !== "undefined" ? MARKETS : null;
  }

  var baseline = {};

  async function syncPrices() {
    var markets = getMarkets();
    if (!markets) return;

    var names = [];
    var pubkeys = [];
    for (var i = 0; i < markets.length; i++) {
      var o = KRONOS.oracles[markets[i].name];
      if (o) {
        names.push(markets[i].name);
        pubkeys.push(o);
      }
    }
    if (!pubkeys.length) return;

    var body = {
      jsonrpc: "2.0",
      id: 1,
      method: "getMultipleAccounts",
      params: [pubkeys, { encoding: "base64", commitment: "confirmed" }],
    };

    var resp = await fetch(rpcUrl(), {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(body),
    });
    var json = await resp.json();
    if (!json.result || !json.result.value) return;

    var changed = false;
    json.result.value.forEach(function (acc, idx) {
      if (!acc || !acc.data || !acc.data[0]) return;
      var price = decodePrice(acc.data[0]);
      if (!isFinite(price) || price <= 0) return;
      var name = names[idx];
      var market = markets.find(function (m) {
        return m.name === name;
      });
      if (!market) return;
      if (baseline[name] === undefined) baseline[name] = price;
      market.price = price;
      market.change = baseline[name]
        ? ((price - baseline[name]) / baseline[name]) * 100
        : 0;
      market.live = true;
      changed = true;
      if (typeof window.kronosRecordSample === "function") {
        window.kronosRecordSample(name, price);
      }
    });

    if (changed) rerender();
    window.__kronosChainLive = true;
  }

  function rerender() {
    try {
      if (typeof renderMarkets === "function") renderMarkets();
      if (typeof renderTicker === "function") renderTicker();
      if (
        typeof renderMarketHeader === "function" &&
        document.getElementById("terminal") &&
        document.getElementById("terminal").classList.contains("active")
      ) {
        renderMarketHeader();
      }
      if (typeof window.kronosDrawChart === "function") {
        window.kronosDrawChart();
      }
    } catch (_) {}
  }

  function start() {
    syncPrices().catch(function () {});
    setInterval(function () {
      syncPrices().catch(function () {});
    }, 5000);
  }

  if (document.readyState === "loading") {
    document.addEventListener("DOMContentLoaded", start);
  } else {
    start();
  }

  window.kronosSyncPrices = syncPrices;
})();
