export type MarketType = "CARDS" | "SEALED" | "INDEX";

export type Market = {
  id: string;
  name: string;
  subtitle: string;
  badge: string;
  live: boolean;
  oracleAddress: string;
  programId: string;
  image?: string;
  /** Keeper API market query param (matches on-chain market_id) */
  priceApiMarket: string;
  type: MarketType;
};

// AUTO-GENERATED by scripts/gen-app-markets.js from the on-chain bootstrap
// manifest (app/src/lib/markets.bootstrap.json). Do not edit by hand; rerun
// the generator after re-bootstrapping markets.
export const MARKETS: Market[] = [
  {
    "id": "WL500",
    "name": "WL500-PERP",
    "subtitle": "WL500 Index · Top 500 Luxury Watches",
    "badge": "INDEX",
    "live": true,
    "oracleAddress": "GF1JfkbgH9EcZXC55DZgxZgEkBBsjk1K9YasTeXsUFaB",
    "programId": "HEZgFANPKb5hCCDZYzz1gdnbsD7C52gAPx5GNU1ifziP",
    "image": "/watches/wl500.jpg",
    "priceApiMarket": "WL500-PERP",
    "type": "INDEX"
  },
  {
    "id": "GOLD",
    "name": "GOLD-PERP",
    "subtitle": "Gold · XAU/USD · Troy Oz Spot",
    "badge": "COMMODITY",
    "live": true,
    "oracleAddress": "69LH9Z52mf25jxvrZMFAnfGp6Sw7whLGs7oKFDAjJKpY",
    "programId": "HEZgFANPKb5hCCDZYzz1gdnbsD7C52gAPx5GNU1ifziP",
    "image": "/watches/gold.jpg",
    "priceApiMarket": "GOLD-PERP",
    "type": "INDEX"
  },
  {
    "id": "SILVER",
    "name": "SILVER-PERP",
    "subtitle": "Silver · XAG/USD · Troy Oz Spot",
    "badge": "COMMODITY",
    "live": true,
    "oracleAddress": "GUPesVEyUiPpYR6Uv5YeStMXxpU9oxZrMujASZSQvxqX",
    "programId": "HEZgFANPKb5hCCDZYzz1gdnbsD7C52gAPx5GNU1ifziP",
    "image": "/watches/silver.jpg",
    "priceApiMarket": "SILVER-PERP",
    "type": "INDEX"
  },
  {
    "id": "PLATINUM",
    "name": "PLATINUM-PERP",
    "subtitle": "Platinum · XPT/USD · Troy Oz Spot",
    "badge": "COMMODITY",
    "live": true,
    "oracleAddress": "FLYN91RZc8Hta45RXcqyiQxyc5nohaotLhvhrYo9zojP",
    "programId": "HEZgFANPKb5hCCDZYzz1gdnbsD7C52gAPx5GNU1ifziP",
    "image": "/watches/platinum.jpg",
    "priceApiMarket": "PLATINUM-PERP",
    "type": "INDEX"
  },
  {
    "id": "ROLEX-SUB",
    "name": "ROLEX-SUB-PERP",
    "subtitle": "Rolex Submariner · 126610LN · Oystersteel",
    "badge": "HOT",
    "live": true,
    "oracleAddress": "GR6QD45YKdgbQxVjzpigN22NsQqDd2TPxjsqoCiw9feJ",
    "programId": "HEZgFANPKb5hCCDZYzz1gdnbsD7C52gAPx5GNU1ifziP",
    "image": "/watches/rolex-sub.jpg",
    "priceApiMarket": "ROLEX-SUB-PERP",
    "type": "CARDS"
  },
  {
    "id": "PATEK-NAUTILUS",
    "name": "PATEK-NAUTILUS-PERP",
    "subtitle": "Patek Philippe · Nautilus 5711/1A",
    "badge": "",
    "live": true,
    "oracleAddress": "5CynvHovsGzyRAhWymJWkcTStwFjHpqxeeu7YWGwJDDN",
    "programId": "HEZgFANPKb5hCCDZYzz1gdnbsD7C52gAPx5GNU1ifziP",
    "image": "/watches/patek-nautilus.jpg",
    "priceApiMarket": "PATEK-NAUTILUS-PERP",
    "type": "CARDS"
  },
  {
    "id": "AP-ROYAL-OAK",
    "name": "AP-ROYAL-OAK-PERP",
    "subtitle": "Audemars Piguet · Royal Oak 15500ST",
    "badge": "NEW",
    "live": true,
    "oracleAddress": "BeKjGVEnwJRGwgRXNMHRUEBkubdAHZDezCJY4AAqUskm",
    "programId": "HEZgFANPKb5hCCDZYzz1gdnbsD7C52gAPx5GNU1ifziP",
    "image": "/watches/ap-royal-oak.jpg",
    "priceApiMarket": "AP-ROYAL-OAK-PERP",
    "type": "CARDS"
  },
  {
    "id": "OMEGA-SPEEDY",
    "name": "OMEGA-SPEEDY-PERP",
    "subtitle": "Omega Speedmaster · Moonwatch Professional",
    "badge": "",
    "live": true,
    "oracleAddress": "HAA3jCpcLFwTB1UCM9LtBNKuZ14z532xqwUob9fyFPR8",
    "programId": "HEZgFANPKb5hCCDZYzz1gdnbsD7C52gAPx5GNU1ifziP",
    "image": "/watches/omega-speedy.jpg",
    "priceApiMarket": "OMEGA-SPEEDY-PERP",
    "type": "CARDS"
  },
  {
    "id": "CARTIER-SANTOS",
    "name": "CARTIER-SANTOS-PERP",
    "subtitle": "Cartier Santos · Large Model WSSA0018",
    "badge": "",
    "live": true,
    "oracleAddress": "4DPvJKYGACSJXieqdCLyfhezzTQatJPP8FntEzSWf9yT",
    "programId": "HEZgFANPKb5hCCDZYzz1gdnbsD7C52gAPx5GNU1ifziP",
    "image": "/watches/cartier-santos.jpg",
    "priceApiMarket": "CARTIER-SANTOS-PERP",
    "type": "CARDS"
  },
  {
    "id": "RM-11",
    "name": "RM-11-PERP",
    "subtitle": "Richard Mille · RM 11-03 · Flyback Chronograph",
    "badge": "HOT",
    "live": true,
    "oracleAddress": "4uzsVSpEYUvRiEicm2DGhmhi5MUwgUxN4xouybFCdPZm",
    "programId": "HEZgFANPKb5hCCDZYzz1gdnbsD7C52gAPx5GNU1ifziP",
    "image": "/watches/rm-11.jpg",
    "priceApiMarket": "RM-11-PERP",
    "type": "CARDS"
  },
  {
    "id": "VC-OVERSEAS",
    "name": "VC-OVERSEAS-PERP",
    "subtitle": "Vacheron Constantin · Overseas 4500V",
    "badge": "",
    "live": true,
    "oracleAddress": "BNBvZtoCEf49iA2G9dRH2KWRZUZp3jveFG2YN9QYKfE1",
    "programId": "HEZgFANPKb5hCCDZYzz1gdnbsD7C52gAPx5GNU1ifziP",
    "image": "/watches/vc-overseas.jpg",
    "priceApiMarket": "VC-OVERSEAS-PERP",
    "type": "CARDS"
  },
  {
    "id": "IWC-PILOT",
    "name": "IWC-PILOT-PERP",
    "subtitle": "IWC Big Pilot · IW501001",
    "badge": "",
    "live": true,
    "oracleAddress": "FsGmgvdkgu7P36yyCKTeZsqVTyTiLNGkViRE4tefNHyE",
    "programId": "HEZgFANPKb5hCCDZYzz1gdnbsD7C52gAPx5GNU1ifziP",
    "image": "/watches/iwc-pilot.jpg",
    "priceApiMarket": "IWC-PILOT-PERP",
    "type": "CARDS"
  },
  {
    "id": "TAG-CARRERA",
    "name": "TAG-CARRERA-PERP",
    "subtitle": "TAG Heuer Carrera · Glassbox Chronograph",
    "badge": "",
    "live": true,
    "oracleAddress": "CUn8JUf882waRGQCnqWMzvw4kvAt7SfvVwLaGPMNqrot",
    "programId": "HEZgFANPKb5hCCDZYzz1gdnbsD7C52gAPx5GNU1ifziP",
    "image": "/watches/tag-carrera.jpg",
    "priceApiMarket": "TAG-CARRERA-PERP",
    "type": "CARDS"
  },
  {
    "id": "ROLEX-DAYTONA",
    "name": "ROLEX-DAYTONA-PERP",
    "subtitle": "Rolex Daytona · 116500LN · Panda Dial",
    "badge": "HOT",
    "live": true,
    "oracleAddress": "bRYw8BCXGbatStJBLR87RC7DXnhCLTaM259GfhiBB1M",
    "programId": "HEZgFANPKb5hCCDZYzz1gdnbsD7C52gAPx5GNU1ifziP",
    "image": "/watches/rolex-daytona.jpg",
    "priceApiMarket": "ROLEX-DAYTONA-PERP",
    "type": "CARDS"
  },
  {
    "id": "PP-ANNUAL",
    "name": "PP-ANNUAL-PERP",
    "subtitle": "Patek Philippe · Annual Calendar 5205G",
    "badge": "",
    "live": true,
    "oracleAddress": "3RPBk1DBkpWquPRVH78cTdytAdsxD3BLbdB65niQVAuv",
    "programId": "HEZgFANPKb5hCCDZYzz1gdnbsD7C52gAPx5GNU1ifziP",
    "image": "/watches/pp-annual.jpg",
    "priceApiMarket": "PP-ANNUAL-PERP",
    "type": "CARDS"
  },
  {
    "id": "AP-OFFSHORE",
    "name": "AP-OFFSHORE-PERP",
    "subtitle": "Audemars Piguet · Royal Oak Offshore",
    "badge": "",
    "live": true,
    "oracleAddress": "APBKgW6vycxVs2XtoSbKC7Xg4BXFeggbYxkz8qDQ1eBn",
    "programId": "HEZgFANPKb5hCCDZYzz1gdnbsD7C52gAPx5GNU1ifziP",
    "image": "/watches/ap-offshore.jpg",
    "priceApiMarket": "AP-OFFSHORE-PERP",
    "type": "CARDS"
  },
  {
    "id": "OMEGA-SEAMASTER",
    "name": "OMEGA-SEAMASTER-PERP",
    "subtitle": "Omega Seamaster · 300M Co-Axial",
    "badge": "",
    "live": true,
    "oracleAddress": "9jZyT7kPCGPWUnTbudMfuZcHZdT8yiQ61hNsNUyq1gRx",
    "programId": "HEZgFANPKb5hCCDZYzz1gdnbsD7C52gAPx5GNU1ifziP",
    "image": "/watches/omega-seamaster.jpg",
    "priceApiMarket": "OMEGA-SEAMASTER-PERP",
    "type": "CARDS"
  },
  {
    "id": "CARTIER-TANK",
    "name": "CARTIER-TANK-PERP",
    "subtitle": "Cartier Tank · Must de Cartier",
    "badge": "",
    "live": true,
    "oracleAddress": "3Ji5xKvRtrEpoM6gSotRkzsbG1cUQ1wrkzbbvb4efyo4",
    "programId": "HEZgFANPKb5hCCDZYzz1gdnbsD7C52gAPx5GNU1ifziP",
    "image": "/watches/cartier-tank.jpg",
    "priceApiMarket": "CARTIER-TANK-PERP",
    "type": "CARDS"
  },
  {
    "id": "HUBLOT-BB",
    "name": "HUBLOT-BB-PERP",
    "subtitle": "Hublot Big Bang · Unico Titanium",
    "badge": "",
    "live": true,
    "oracleAddress": "HLwHoHsn4mCuarN4DrLkUzJKh8zJqUg7QcBUc7bC2z6v",
    "programId": "HEZgFANPKb5hCCDZYzz1gdnbsD7C52gAPx5GNU1ifziP",
    "image": "/watches/hublot-bb.jpg",
    "priceApiMarket": "HUBLOT-BB-PERP",
    "type": "CARDS"
  },
  {
    "id": "JLC-REVERSO",
    "name": "JLC-REVERSO-PERP",
    "subtitle": "Jaeger-LeCoultre · Reverso Classic",
    "badge": "",
    "live": true,
    "oracleAddress": "3ZBRh6H9eLFfJ5UJse41WS9wvGmZ8DATLfJNnCvTXpA2",
    "programId": "HEZgFANPKb5hCCDZYzz1gdnbsD7C52gAPx5GNU1ifziP",
    "image": "/watches/jlc-reverso.jpg",
    "priceApiMarket": "JLC-REVERSO-PERP",
    "type": "CARDS"
  },
  {
    "id": "PANERAI-LUM",
    "name": "PANERAI-LUM-PERP",
    "subtitle": "Panerai Luminor · Marina 1312",
    "badge": "",
    "live": true,
    "oracleAddress": "4FeYrkvD4U5FWMRFS39MmbvUcUUjZbVYPYag3yKcQoQQ",
    "programId": "HEZgFANPKb5hCCDZYzz1gdnbsD7C52gAPx5GNU1ifziP",
    "image": "/watches/panerai-lum.jpg",
    "priceApiMarket": "PANERAI-LUM-PERP",
    "type": "CARDS"
  },
  {
    "id": "BREITLING-NAV",
    "name": "BREITLING-NAV-PERP",
    "subtitle": "Breitling Navitimer · B01 Chronograph",
    "badge": "",
    "live": true,
    "oracleAddress": "F54GsLSG9tTai34BCmBUSjhyVCGVgQdbUUzdbLWSisLf",
    "programId": "HEZgFANPKb5hCCDZYzz1gdnbsD7C52gAPx5GNU1ifziP",
    "image": "/watches/breitling-nav.jpg",
    "priceApiMarket": "BREITLING-NAV-PERP",
    "type": "CARDS"
  },
  {
    "id": "ROLEX-GMT",
    "name": "ROLEX-GMT-PERP",
    "subtitle": "Rolex GMT-Master II · 126710BLNR",
    "badge": "",
    "live": true,
    "oracleAddress": "FPsnY6J74x12aYdLPYHkpFFLZnp61X7CwKqUUNsfhN57",
    "programId": "HEZgFANPKb5hCCDZYzz1gdnbsD7C52gAPx5GNU1ifziP",
    "image": "/watches/rolex-gmt.jpg",
    "priceApiMarket": "ROLEX-GMT-PERP",
    "type": "CARDS"
  }
];
